name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16
      - nscloud-exp-runner-tool-cache-50gb
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-gha-demo-frostdb
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false

      - name: Setup Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod

      - name: Test
        run: go test -short -race -tags assert,debug -v ./...
