name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: [main]
    paths:
      - "**.go"
      - .golangci.yml
      - .github/workflows/golangci-lint.yml
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - .golangci.yml
      - .github/workflows/golangci-lint.yml
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: nscloud-ubuntu-22.04-amd64-8x16
    continue-on-error: true
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.51.2
